# config/data-catalog-tags/pubsub-gcs-dataflow.yaml

project_id: "sw-dev-prj-sandbox"   # file-level default
location:   "us-east4"             # file-level default

tags:

  historian-stream-messageid:
    parent:   "projects/sw-dev-prj-sandbox/datasets/pubsub_gcs_dataflow/tables/historian_stream"
    column:   "messageid"
    template: "projects/sw-dev-prj-sandbox/locations/us-east4/tagTemplates/data_classification"
    fields:
      classification:
        enum_value: "Confidential"
      source:
        string_value: "DB-1 Table-A Column-B"