- name:          "copyjob_streaming_dataset_sw"
  destination_project_id:    "sw-dev-prj-itp-secrets"
  destination_friendly_name: "SW copyjob Streaming Dataset"
  destination_description:   "SW copyjob Streaming Dataset - Main streaming tables"
  destination_location:      "us-east4"

  options:
    default_table_expiration_ms:     null
    default_partition_expiration_ms: null
    delete_contents_on_destroy:      false

  source:
    project:  "sw-dev-prj-sandbox"
    dataset:  "pubsub_gcs_dataflow"
    routine:  "sp_clone_all_tables_sw"
    location: "us-east4"

  job:
    job_id:         "invoke-sp-clone-all-tables-v6"
    use_legacy_sql: false

  schedule:
    display_name:    "Nightly-Dev-Reset-DEV"
    schedule:        "every 24 hours"
    service_account: "dataflow-runner@sw-dev-prj-sandbox.iam.gserviceaccount.com"