log_project_id: "sw-dev-prj-sandbox"

tables:

  historian-stream:
    dataset_id:   "pubsub_gcs_dataflow"
    table_id:     "historian_stream"
    taxonomy_key: "data-classification"     # ← matches local.taxonomy_configs key

    columns:
      - name:        "messageid"
        type:        "INTEGER"
        mode:        "NULLABLE"
        description: "Unique message identifier"
        policy_tag:  "L3-Confidential"          # → taxonomy_key/confidential tag ID

      - name:        "quality"
        type:        "INTEGER"
        mode:        "NULLABLE"
        description: "Source device identifier"
        policy_tag:  "L4-Restricted"